CREATE TABLE CB_FILE
  (
    FILEUSERID INTEGER 	           NOT NULL ,
    FILEID     INTEGER 	           NOT NULL ,
    FILENAME   VARCHAR2 (500 CHAR) NOT NULL ,
    FILEEXT    VARCHAR2 (15  CHAR) NOT NULL ,
    FILEDATE   TIMESTAMP           NOT NULL ,
    FILEHASH   VARCHAR2 (200 CHAR) NOT NULL
  ) ;
ALTER TABLE CB_FILE ADD CONSTRAINT PK_FILE PRIMARY KEY ( FILEID ) ;


CREATE TABLE CB_TEMPLINK
  (
    TLINKID     INTEGER NOT NULL ,
    TLINKFILEID INTEGER NOT NULL ,
    TLINKPATH   VARCHAR2 (100 CHAR) ,
    TLINKEXPIRE DATE
  ) ;
ALTER TABLE CB_TEMPLINK ADD CONSTRAINT PK_TEMPLINK PRIMARY KEY ( TLINKID ) ;


  CREATE TABLE CB_ROLE
  ( 
    ROLEID    INTEGER NOT NULL , 
    ROLELABEL VARCHAR2 (20 CHAR) 
  ) ;
ALTER TABLE CB_ROLE ADD CONSTRAINT PK_ROLE PRIMARY KEY ( ROLEID ) ;


CREATE TABLE CB_USER
  (
    USERID       INTEGER             NOT NULL ,
    USERMAIL     VARCHAR2 (70  CHAR) NOT NULL ,
    USERPASSHASH VARCHAR2 (150 CHAR) NOT NULL ,
    USERSALT     VARCHAR2 (200 CHAR) NOT NULL ,
    USERNAME 	 VARCHAR2 (70  CHAR) NOT NULL ,
    USERNOTES    VARCHAR2 (100 CHAR) ,
    USERPIC      VARCHAR2 (100 CHAR) 
  ) ;
ALTER TABLE CB_USER ADD CONSTRAINT PK_USER PRIMARY KEY ( USERID ) ;


CREATE TABLE CB_USERROLE
  (
    UR_USERID INTEGER NOT NULL ,
    UR_ROLEID INTEGER NOT NULL
  ) ;
ALTER TABLE CB_USERROLE ADD CONSTRAINT PK_USERROLE PRIMARY KEY ( UR_USERID, UR_ROLEID ) ;


CREATE TABLE CB_USERFILE
  (
    UF_USERID INTEGER NOT NULL ,
    UF_FILEID INTEGER NOT NULL ,
    UF_DEL	  DATE 
  ) ;
ALTER TABLE CB_USERFILE ADD CONSTRAINT PK_USERFILE PRIMARY KEY ( UF_USERID, UF_FILEID ) ;


CREATE TABLE CB_AUTHHASH
  (
    AH_USERID INTEGER            NOT NULL ,
    AH_HASH   VARCHAR2 (70 CHAR) NOT NULL ,
    AH_EXPIRE DATE 
  ) ;
ALTER TABLE CB_AUTHHASH ADD CONSTRAINT PK_AUTHHASH PRIMARY KEY ( AH_USERID, AH_HASH ) ;


ALTER TABLE CB_FILE     ADD CONSTRAINT FK_FILE_USERID_USER     FOREIGN KEY ( FILEUSERID )  REFERENCES CB_USER ( USERID ) ;
ALTER TABLE CB_TEMPLINK ADD CONSTRAINT FK_TEMPLINK_FILEID_FILE FOREIGN KEY ( TLINKFILEID ) REFERENCES CB_FILE ( FILEID ) ;
ALTER TABLE CB_USERROLE ADD CONSTRAINT FK_USERROLE_USERID_USER FOREIGN KEY ( UR_USERID )   REFERENCES CB_USER ( USERID ) ;
ALTER TABLE CB_USERROLE ADD CONSTRAINT FK_USERROLE_ROLEID_ROLE FOREIGN KEY ( UR_ROLEID )   REFERENCES CB_ROLE ( ROLEID ) ;
ALTER TABLE CB_USERFILE ADD CONSTRAINT FK_USERFILE_USERID_USER FOREIGN KEY ( UF_USERID )   REFERENCES CB_USER ( USERID ) ;
ALTER TABLE CB_USERFILE ADD CONSTRAINT FK_USERFILE_FILEID_FILE FOREIGN KEY ( UF_FILEID )   REFERENCES CB_FILE ( FILEID ) ; 
ALTER TABLE CB_AUTHHASH ADD CONSTRAINT FK_AUTHHASH_USERID_USER FOREIGN KEY ( AH_USERID )   REFERENCES CB_USER ( USERID ) ; 










